
#ifdef MAIN_DEF
	#define MAIN_GLOBE
#else
	#define MAIN_GLOBE		extern
#endif

#include "app_cfg.h"
#include "bsp_os.h"


#define	TASK_START_PRIO       	6
#define	TASK_SHELL_PRIO		    7	
#define	TASK_EthRelink_PRIO		9	
#define	TASK_GPS_PRIO			23	
#define	TASK_D350_SHELL_PRIO	25
#define	TASK_AP_PRIO		    26	
#define	TASK_RESERVD_PRIO		27	

#define  	TASK_EthRelink_STK_SIZE            	TASK_STK_SIZE_256
#define  	TASK_D350_SHELL_STK_SIZE            TASK_STK_SIZE_256
#define  	TASK_AP_STK_SIZE            		TASK_STK_SIZE_256
#define  	TASK_RESERVD_STK_SIZE       TASK_STK_SIZE_256
#define  	TASK_GPS_STK_SIZE            		TASK_STK_SIZE_1024
#define  	TASK_START_STK_SIZE            		TASK_STK_SIZE_1024 
#define  	TASK_SHELL_STK_SIZE            		(TASK_STK_SIZE_512 + TASK_STK_SIZE_256)

MAIN_GLOBE OS_TCB	TaskEthRelinkTCB;
MAIN_GLOBE CPU_STK	TaskEthRelinkStk[TASK_EthRelink_STK_SIZE];

MAIN_GLOBE OS_TCB	TaskGPSTCB;
MAIN_GLOBE CPU_STK	TaskGPSStk[TASK_GPS_STK_SIZE];

MAIN_GLOBE OS_TCB	TaskShellTCB;
MAIN_GLOBE CPU_STK	TaskShellStk[TASK_SHELL_STK_SIZE];

MAIN_GLOBE OS_TCB	TaskStartTCB;
MAIN_GLOBE CPU_STK	TaskStartStk[TASK_START_STK_SIZE];

MAIN_GLOBE OS_TCB	TaskD350ShellTCB;
MAIN_GLOBE CPU_STK	TaskD350ShellStk[TASK_D350_SHELL_STK_SIZE];

MAIN_GLOBE OS_TCB	TaskAPTCB;
MAIN_GLOBE CPU_STK	TaskAPStk[TASK_AP_STK_SIZE];

MAIN_GLOBE OS_TCB	TaskReservdTCB;
MAIN_GLOBE CPU_STK	TaskReservdStk[TASK_RESERVD_STK_SIZE];

